name: "CI"

on:
  push:
    paths:
      - "**.php"
      - "phpcs.xml"
      - ".github/workflows/phpcs.yml"

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # important!

      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version

      - uses: tinovyatkin/action-php-codesniffer@v1
        with:
          files: "**.php" # you may customize glob as needed
          phpcs_path: php phpcs.phar
          standard: phpcs.xml
  phpcs2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: shivammathur/setup-php@2.15.0
        with:
          php-version: 8.1
          coverage: none
          tools: cs2pr

      - name: Install dependencies
        run: composer install

      - name: Run PHP Codesniffer
        run: vendor/bin/phpcs --report=checkstyle -q | cs2pr --graceful-warnings
