name: WPCS checker
on: push
jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: shivammathur/setup-php@2.15.0
        with:
          php-version: 8.2
          coverage: none
          tools: cs2pr

      - name: Run PHP Codesniffer
        run: ./vendor/bin/phpcs

