name: CI Build
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: Set Node version to 12
      uses: actions/setup-node@v1
      with:
        version: 12

    - name: Run composer install
      run: |
        composer install --prefer-dist

    - name: Run PHPCS Coding Standards
      run: |
        /www/vendor/bin/phpcs $GITHUB_WORKSPACE

    - name: Create a built branch
      run: |
        BRANCH_NAME=$(echo $GITHUB_REF | grep -oP '(?<=refs\/heads\/).*')
        rm .gitignore
        mv .deployignore .gitignore
        git config --global user.email "ci@company.com"
        git config --global user.name "Company CI"
        git remote set-url origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git
        git checkout -b $BRANCH_NAME-built
        git add -A && git commit -m "built from $GITHUB_SHA"
        git push --force -u origin $BRANCH_NAME-built
