name: "CI"

on: [push]
jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.2']
        dependencies:
          - lowest
          - highest

    name: phpunit (${{ matrix.php-versions }}-${{ matrix.dependencies }})

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: shivammathur/setup-php@2.15.0
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
        if: matrix.php-versions != '8.2' || matrix.dependencies != 'highest'

      - uses: shivammathur/setup-php@2.15.0
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: pcov
        if: matrix.php-versions == '8.2' && matrix.dependencies == 'highest'

      - name: Setup problem matcher for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        if: matrix.dependencies == 'lowest'
        run: composer update --prefer-lowest

      - name: Install dependencies
        if: matrix.dependencies == 'highest'
        run: composer install

      - name: Run PHPUnit
        run: vendor/bin/phpunit
        if: matrix.php-versions != '8.2' || matrix.dependencies != 'highest'

      - name: Run PHPUnit with coverage
        run: vendor/bin/phpunit --coverage-clover=coverage.xml
        if: matrix.php-versions == '8.2' && matrix.dependencies == 'highest'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        if: matrix.php-versions == '8.2' && matrix.dependencies == 'highest'

  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: shivammathur/setup-php@2.15.0
        with:
          php-version: 8.1
          coverage: none
          tools: cs2pr

      - name: Install dependencies
        run: composer install

      - name: Run PHP Codesniffer
        run: vendor/bin/phpcs --report=checkstyle -q | cs2pr --graceful-warnings
